name: meme-challenge

services:
  postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
    ports:
      - 28080:8080
    depends_on:
      - keycloak-postgres
    command: start-dev
  keycloak-postgres:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
    ports:
      - 25432:5432
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  keycloak_postgres_data:
